version: 2
registries:
  maven-github:
    type: maven-repository
    url: https://maven.pkg.github.com/samq-democorp/text4shell
    username: samq-ws
    password: ${{secrets.GH_TOKEN}}
updates:
  - package-ecosystem: "maven"
    directory: "/"
    registries:
      - maven-github
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
