version: 2
registries:
  maven-github:
    type: maven-repository
    url: https://maven.pkg.github.com/samq-democorp/text4shell
    username: samq-ws
    password: ${{secrets.GH_TOKEN}}
  maven-central:
    type: maven-repository
    url: https://repo.maven.apache.org/maven2/
updates:
  - package-ecosystem: "maven"
    directory: "/"
    registries:
      - maven-github
      - maven-central
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
